AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SmartURL - Serverless URL Shortener

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    MemorySize: 256

Resources:
  SmartURLFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: src.main.lambda_handler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
